spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/test
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: "super-secret-key-super-secret-key"
  expiration: 86400000